services:
  ialvaro:
    container_name: ialvaro
    image: ghcr.io/pnpm/pnpm:latest
    restart: unless-stopped
    command: >
      sh -c
      "
      pnpm runtime set node latest -g
      && cd /project
      && pnpm install
      && pnpm run build
      && exec node dist/server/entry.mjs
      "
    volumes:
      - .:/project
    networks: [proxy]
    labels:
      caddy: ialvaro.com, azama.es
      caddy.import: cloudflare
      caddy.reverse_proxy: '{{upstreams 4321}}'

networks:
  proxy:
    external: {}
