services:
  ialvaro:
    container_name: ialvaro
    image: node:alpine
    restart: unless-stopped
    command: >
      sh -c
      "
      cd /project
      && npm install
      && npm run build
      && node dist/server/entry.mjs &
      tail -f /dev/null
      "
    volumes:
      - .:/project
    networks: [proxy]
    labels:
      caddy: ialvaro.com, azama.es
      caddy.import: cloudflare
      caddy.reverse_proxy: '{{upstreams 4321}}'

networks:
  proxy:
    external: {}
